import { StyleSheet } from 'react-native';
import { colors } from '../../theme';

export const styles = StyleSheet.create({
  homeMain: { flex: 1 },
  homeContent: { paddingTop: 18, paddingHorizontal: 12, paddingBottom: 24, gap: 16 },
  storyRail: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    left: 0,
    width: 102,
    paddingTop: 44,
    backgroundColor: colors.surface,
    borderRightWidth: 1,
    borderRightColor: colors.border,
    zIndex: 3,
    elevation: 8,
  },
  storyRailRight: {
    left: undefined,
    right: 0,
    borderRightWidth: 0,
    borderLeftWidth: 1,
    borderLeftColor: colors.border,
  },
  storyRailDark: { backgroundColor: colors.dark, borderRightColor: colors.border },
  storyRailTitle: {
    color: colors.primary,
    fontSize: 11,
    fontWeight: '900',
    letterSpacing: 0.6,
    textAlign: 'center',
    marginHorizontal: 12,
    marginBottom: 16,
    textTransform: 'uppercase',
  },
  storyItem: { alignItems: 'center', gap: 6, marginVertical: 4 },
  storyRing: {
    width: 66,
    height: 66,
    borderRadius: 33,
    borderWidth: 2.2,
    borderColor: colors.primary,
    padding: 2.5,
    position: 'relative',
    alignItems: 'center',
    justifyContent: 'center',
  },
  storyViewed: { borderColor: colors.border },
  storyAvatar: {
    width: '100%',
    height: '100%',
    borderRadius: 30,
    backgroundColor: colors.surfaceAlt,
  },
  storyName: {
    fontSize: 10,
    fontWeight: '700',
    color: colors.text,
    textAlign: 'center',
    width: 72,
  },
  storyNameDark: { color: '#C5C9E0' },
  addStoryRing: { borderStyle: 'dashed', borderColor: colors.muted },
  storyAddBadge: {
    position: 'absolute',
    right: -2,
    bottom: -2,
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: colors.primary,
    borderWidth: 1.8,
    borderColor: colors.surface,
    alignItems: 'center',
    justifyContent: 'center',
  },
  storyRailHandlePosition: {
    position: 'absolute',
    top: 0,
    zIndex: 999,
  },
  storyRailHandle: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.primary,
    borderTopRightRadius: 18,
    borderBottomRightRadius: 18,
    paddingLeft: 12,
    paddingRight: 12,
    height: 38,
    gap: 6,
    elevation: 6,
    shadowColor: colors.primary,
    shadowOpacity: 0.35,
    shadowRadius: 8,
    shadowOffset: { width: 2, height: 2 },
  },
  storyRailHandleRight: {
    borderTopRightRadius: 0,
    borderBottomRightRadius: 0,
    borderTopLeftRadius: 18,
    borderBottomLeftRadius: 18,
    paddingLeft: 12,
    paddingRight: 12,
    shadowOffset: { width: -2, height: 2 },
  },
  storyRailHandlePressed: { opacity: 0.85 },
  storyRailHandleText: { color: '#fff', fontSize: 11, fontWeight: '900', letterSpacing: 0.6 },
  storyRailHandleIcon: {
    width: 7,
    height: 12,
    tintColor: '#fff',
    transform: [{ rotate: '-90deg' }],
  },
  storyRailHandleDot: {
    position: 'absolute',
    top: 8,
    right: 5,
    width: 7,
    height: 7,
    borderRadius: 4,
    backgroundColor: '#FF6B78',
    borderWidth: 1,
    borderColor: '#fff',
  },
  storyRailContent: { alignItems: 'center', gap: 14, paddingBottom: 110 },
  homeActivityCard: {
    gap: 10,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    borderRadius: 20,
    padding: 16,
    borderWidth: 1,
    shadowColor: '#6C5DD3',
    shadowOpacity: 0.05,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
  },
  accessGate: {
    borderRadius: 19,
    padding: 14,
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: 11,
    borderWidth: 1,
    borderColor: '#F1D3E2',
  },
  accessGateIcon: {
    width: 43,
    height: 43,
    borderRadius: 14,
    backgroundColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  accessGateTitle: { color: colors.text, fontSize: 14, fontWeight: '900', marginBottom: 2 },
  accessGateText: { color: colors.muted, fontSize: 10, lineHeight: 14, fontWeight: '600' },
  accessGateButton: {
    width: '100%',
    minHeight: 38,
    borderRadius: 12,
    backgroundColor: colors.primary,
    flexDirection: 'row',
    gap: 6,
    alignItems: 'center',
    justifyContent: 'center',
  },
  accessGateButtonText: { color: '#fff', fontSize: 11, fontWeight: '900' },
  homeActivityRow: {
    minHeight: 62,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  homeActivityIcon: {
    width: 38,
    height: 38,
    borderRadius: 13,
    backgroundColor: colors.surfaceAlt,
    alignItems: 'center',
    justifyContent: 'center',
  },
  purposeRow: { gap: 12 },
  recommendedPeopleRow: { gap: 10, paddingRight: 12 },
  recommendedPersonCard: { width: 150 },
  purposeCard: {
    width: 145,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 18,
    padding: 15,
    gap: 10,
    borderTopWidth: 5,
    elevation: 1.5,
    shadowColor: '#000',
    shadowOpacity: 0.04,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 1 },
  },
  storyViewer: { flex: 1, backgroundColor: '#000', justifyContent: 'center' },
  storyViewerImage: { width: '100%', height: '100%' },
  storyTopShade: { position: 'absolute', top: 0, left: 0, right: 0, height: 130 },
  storyBottomShade: { position: 'absolute', bottom: 0, left: 0, right: 0, height: 145 },
  storyViewerHeader: {
    position: 'absolute',
    top: 48,
    left: 16,
    right: 16,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 11,
  },
  storyViewerAvatar: {
    width: 38,
    height: 38,
    borderRadius: 19,
    borderWidth: 1.5,
    borderColor: '#fff',
  },
  storyViewerAvatarFallback: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: 'rgba(255,255,255,0.25)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  storyViewerName: { color: '#fff', fontWeight: '800', fontSize: 13.5 },
  storyViewerTime: { color: 'rgba(255,255,255,.65)', fontSize: 10.5, marginTop: 1 },
  storyHeaderButton: { padding: 5 },
  storyPrevious: { position: 'absolute', left: 0, top: 120, bottom: 120, width: '30%' },
  storyNext: { position: 'absolute', right: 0, top: 120, bottom: 120, width: '70%' },
  storyViews: {
    position: 'absolute',
    bottom: 84,
    alignSelf: 'center',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: 'rgba(0,0,0,.45)',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 99,
  },
  storyViewsText: { color: '#fff', fontSize: 11, fontWeight: '700' },
  storyInteractionBar: {
    position: 'absolute',
    bottom: 24,
    left: 16,
    right: 16,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
  },
  storyReplyInput: {
    flex: 1,
    height: 42,
    borderWidth: 1.2,
    borderColor: 'rgba(255,255,255,.36)',
    borderRadius: 21,
    paddingHorizontal: 12,
    color: '#fff',
    fontSize: 13,
  },
  storyReaction: { fontSize: 24, padding: 3 },
  storyReactionSummary: {
    position: 'absolute',
    bottom: 84,
    alignSelf: 'center',
    flexDirection: 'row',
    gap: 8,
  },
  storyReactionCount: {
    color: '#fff',
    backgroundColor: 'rgba(0,0,0,0.5)',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
    fontSize: 11,
    fontWeight: '800',
  },
  storyReactionBurst: {
    position: 'absolute',
    alignSelf: 'center',
    justifyContent: 'center',
    zIndex: 99,
  },
  storyReactionBurstText: { fontSize: 92 },
  storyProgressRow: {
    position: 'absolute',
    top: 38,
    left: 12,
    right: 12,
    flexDirection: 'row',
    gap: 5,
  },
  storyProgress: {
    flex: 1,
    height: 4,
    backgroundColor: 'rgba(255,255,255,.22)',
    borderRadius: 99,
    overflow: 'hidden',
    borderWidth: 0.5,
    borderColor: 'rgba(255,255,255,.18)',
  },
  storyProgressActive: {
    height: '100%',
    borderRadius: 99,
    shadowColor: colors.primary,
    shadowOpacity: 0.45,
    shadowRadius: 6,
  },
  storyViewersSheet: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: colors.surface,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    padding: 20,
    minHeight: 280,
    maxHeight: 520,
  },
  storyViewersHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 18,
  },
  storyViewersTitle: { fontSize: 16, fontWeight: '900', color: colors.text },
  storyViewerRow: { flexDirection: 'row', alignItems: 'center', gap: 11 },
  eyebrow: {
    color: colors.primary,
    fontSize: 10,
    fontWeight: '900',
    letterSpacing: 1,
    marginBottom: 2,
  },
  topRow: {
    minHeight: 56,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 18,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
    backgroundColor: colors.bg,
  },
  homeHeaderActions: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  coinHeaderChip: {
    height: 38,
    paddingHorizontal: 12,
    borderRadius: 19,
    borderWidth: 1,
    borderColor: 'rgba(108, 93, 211, 0.15)',
    backgroundColor: 'rgba(108, 93, 211, 0.06)',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
  },
  coinHeaderIcon: {
    width: 22,
    height: 22,
    borderRadius: 11,
    alignItems: 'center',
    justifyContent: 'center',
  },
  coinHeaderValue: { color: colors.primary, fontSize: 13, fontWeight: '800' },
  fab: {
    position: 'absolute',
    bottom: 24,
    right: 20,
    width: 58,
    height: 58,
    borderRadius: 29,
    backgroundColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 8,
    shadowColor: colors.primary,
    shadowOpacity: 0.45,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
  },
  fabMenu: {
    position: 'absolute',
    bottom: 92,
    right: 20,
    alignItems: 'flex-end',
    gap: 12,
  },
  fabAction: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  fabLabel: {
    color: colors.text,
    fontSize: 12,
    fontWeight: '800',
    backgroundColor: colors.surface,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 10,
    overflow: 'hidden',
    elevation: 3,
    shadowColor: '#000',
    shadowOpacity: 0.08,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 2 },
  },
  fabSmallButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 5,
    shadowColor: colors.primary,
    shadowOpacity: 0.3,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 3 },
  },
  createCommunityCopy: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  createCommunityIcon: {
    width: 48,
    height: 48,
    borderRadius: 16,
    backgroundColor: colors.surfaceAlt,
    alignItems: 'center',
    justifyContent: 'center',
  },
  joinedBanner: {
    gap: 16,
    borderColor: colors.border,
    backgroundColor: colors.surfaceAlt,
  },
  joinedTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 11,
  },
  joinedCheck: {
    width: 36,
    height: 36,
    borderRadius: 12,
    backgroundColor: colors.success,
    alignItems: 'center',
    justifyContent: 'center',
  },
  communityActionGrid: {
    flexDirection: 'row',
    gap: 10,
  },
  communityAction: {
    flex: 1,
    minHeight: 124,
    borderRadius: 16,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    padding: 13,
    gap: 5,
  },
  communityActionIcon: {
    width: 39,
    height: 39,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 4,
  },
  communityActionTitle: {
    color: colors.text,
    fontSize: 13,
    fontWeight: '800',
  },
  communityActionText: {
    color: colors.muted,
    fontSize: 10,
  },
  purposeIcon: {
    width: 40,
    height: 40,
    borderRadius: 13,
    alignItems: 'center',
    justifyContent: 'center',
  },
  cardTitle: { color: colors.text, fontSize: 15, fontWeight: '800' },
  smallMuted: { color: colors.muted, fontSize: 12, lineHeight: 17 },
  listRow: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  unread: {
    minWidth: 20,
    height: 20,
    paddingHorizontal: 5,
    borderRadius: 10,
    backgroundColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  unreadText: { color: '#fff', fontSize: 10, fontWeight: '900' },
  handle: { color: colors.muted, fontWeight: '600' },
  profileHero: { alignItems: 'center', gap: 8, paddingVertical: 14 },
  trust: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    backgroundColor: colors.surfaceAlt,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 99,
  },
  trustText: { color: colors.info, fontSize: 11, fontWeight: '800' },
  twoButtons: { flexDirection: 'row', gap: 10 },
  connectHero: { alignItems: 'center', gap: 12, paddingVertical: 30 },
  connectIcon: {
    width: 96,
    height: 96,
    borderRadius: 34,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.primary,
  },
  centerText: { textAlign: 'center', color: colors.muted },
  safety: {
    flexDirection: 'row',
    gap: 10,
    padding: 15,
    backgroundColor: colors.surfaceAlt,
    borderRadius: 15,
  },
  searching: { flex: 1, justifyContent: 'center', alignItems: 'center', gap: 22 },
  radar: {
    width: 180,
    height: 180,
    borderRadius: 90,
    backgroundColor: 'rgba(124, 58, 237, 0.15)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  radarInner: {
    width: 92,
    height: 92,
    borderRadius: 46,
    backgroundColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  time: { color: colors.muted, fontSize: 10 },
  chatHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    padding: 10,
    backgroundColor: colors.surface,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  onlineText: { color: colors.success, fontSize: 10 },
  chatBody: { flex: 1, padding: 16, gap: 10 },
  chatBodyContent: { flexGrow: 1, gap: 10, paddingBottom: 12 },
  typingText: { color: colors.primary, fontSize: 11, fontWeight: '700', marginTop: 3 },
  replyQuote: {
    borderLeftWidth: 3,
    borderLeftColor: colors.primary,
    paddingLeft: 8,
    marginBottom: 6,
    opacity: 0.88,
  },
  messageReactions: { marginTop: 5, fontSize: 16 },
  pendingReply: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingHorizontal: 12,
    paddingVertical: 8,
    backgroundColor: colors.surfaceAlt,
    borderTopWidth: 1,
    borderTopColor: colors.border,
  },
  connectTimer: {
    minHeight: 38,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 7,
    backgroundColor: colors.surfaceAlt,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  connectTimerText: { color: colors.primary, fontSize: 12, fontWeight: '900' },
  errorText: { color: colors.danger, fontSize: 13, marginBottom: 10 },
  inlineError: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 7,
    padding: 10,
    borderRadius: 12,
    backgroundColor: 'rgba(239, 68, 68, 0.1)',
  },
  inlineErrorText: { flex: 1, color: colors.danger, fontSize: 11 },
  chatNotice: {
    alignSelf: 'center',
    flexDirection: 'row',
    gap: 7,
    backgroundColor: colors.surfaceAlt,
    borderRadius: 99,
    paddingHorizontal: 12,
    paddingVertical: 7,
  },
  bubble: { maxWidth: '82%', paddingHorizontal: 12, paddingVertical: 10, borderRadius: 17 },
  mine: { alignSelf: 'flex-end', backgroundColor: colors.primary, borderBottomRightRadius: 5 },
  theirs: {
    alignSelf: 'flex-start',
    backgroundColor: colors.surface,
    borderBottomLeftRadius: 5,
    borderWidth: 1,
    borderColor: colors.border,
  },
  bubbleTime: { color: colors.muted, fontSize: 9, marginTop: 4, textAlign: 'right' },
  composer: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    gap: 8,
    padding: 10,
    backgroundColor: colors.surface,
    borderTopWidth: 1,
    borderTopColor: colors.border,
  },
  blockedComposer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    padding: 16,
    borderTopWidth: 1,
    borderTopColor: colors.border,
    backgroundColor: colors.surfaceAlt,
  },
  pendingAttachment: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingHorizontal: 12,
    paddingVertical: 9,
    backgroundColor: colors.surfaceAlt,
    borderTopWidth: 1,
    borderTopColor: colors.border,
  },
  pendingImage: { width: 48, height: 48, borderRadius: 11 },
  attachmentImage: {
    width: '100%',
    height: 220,
    borderRadius: 18,
    backgroundColor: colors.surfaceAlt,
    marginBottom: 7,
  },
  createPostHero: {
    minHeight: 82,
    borderRadius: 20,
    padding: 15,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    borderWidth: 1,
    borderColor: colors.border,
  },
  createPostStep: {
    width: 42,
    height: 42,
    borderRadius: 14,
    backgroundColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  createPostHeroTitle: { color: colors.text, fontSize: 16, fontWeight: '900', marginBottom: 3 },
  postComposerCard: { padding: 15, gap: 10 },
  createAuthorRow: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  draftBadge: {
    paddingHorizontal: 7,
    paddingVertical: 4,
    borderRadius: 8,
    backgroundColor: colors.surfaceAlt,
  },
  draftBadgeText: { color: colors.primary, fontSize: 8, fontWeight: '900', letterSpacing: 0.7 },
  postComposerInput: {
    minHeight: 135,
    color: colors.text,
    fontSize: 17,
    lineHeight: 25,
    textAlignVertical: 'top',
    paddingVertical: 10,
  },
  composerFooter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderTopWidth: 1,
    borderTopColor: colors.border,
    paddingTop: 10,
  },
  characterCount: { color: colors.primary, fontSize: 10, fontWeight: '900' },
  postTypeGrid: { flexDirection: 'row', gap: 8 },
  postTypeOption: {
    flex: 1,
    minHeight: 68,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 5,
  },
  postTypeOptionActive: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
    elevation: 3,
    shadowColor: colors.primary,
    shadowOpacity: 0.22,
    shadowRadius: 7,
  },
  postTypeText: { color: colors.text, fontSize: 10, fontWeight: '800' },
  createImagePreview: {
    borderRadius: 18,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: colors.border,
  },
  visibilitySelector: {
    flexDirection: 'row',
    gap: 9,
    padding: 6,
    borderRadius: 16,
    backgroundColor: colors.surfaceAlt,
  },
  messageAttachment: { marginBottom: 7 },
  messageImage: { width: 210, height: 145, borderRadius: 12, backgroundColor: colors.border },
  fileAttachment: { minWidth: 210, flexDirection: 'row', alignItems: 'center', gap: 9 },
  fileName: { color: colors.text, fontSize: 12, fontWeight: '800' },
  composerInput: {
    flex: 1,
    minHeight: 43,
    maxHeight: 100,
    backgroundColor: colors.bg,
    borderRadius: 16,
    paddingHorizontal: 12,
    paddingVertical: 11,
    color: colors.text,
  },
  send: {
    width: 43,
    height: 43,
    borderRadius: 15,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.primary,
  },
  profileSummary: { flexDirection: 'row', gap: 15, alignItems: 'center' },
  stats: { flexDirection: 'row', marginTop: 10, gap: 18 },
  stat: { color: colors.muted, fontSize: 10, textAlign: 'center' },
  statNum: { color: colors.text, fontSize: 17, fontWeight: '900' },
  // New profile hero card (ProfileScreen)
  profileHeroCard: {
    backgroundColor: colors.surface,
    borderRadius: 24,
    paddingTop: 28,
    paddingBottom: 20,
    paddingHorizontal: 12,
    alignItems: 'center',
    marginBottom: 8,
    elevation: 2,
    shadowColor: '#000',
    shadowOpacity: 0.06,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 2 },
  },
  profileAvatarWrap: {
    marginBottom: 12,
    borderRadius: 999,
    borderWidth: 3,
    borderColor: colors.primary,
    padding: 2,
  },
  profileHeroName: {
    fontSize: 22,
    fontWeight: '900',
    color: colors.text,
    textAlign: 'center',
  },
  profileHeroHandle: {
    fontSize: 13,
    color: colors.muted,
    marginTop: 2,
    marginBottom: 16,
    textAlign: 'center',
  },
  profileHeroStats: {
    flexDirection: 'row',
    alignItems: 'center',
    width: '100%',
    backgroundColor: colors.surfaceAlt,
    borderRadius: 16,
    paddingVertical: 14,
    marginBottom: 16,
  },
  profileHeroStat: {
    flex: 1,
    alignItems: 'center',
  },
  profileHeroStatNum: {
    fontSize: 20,
    fontWeight: '900',
    color: colors.text,
  },
  profileHeroStatLabel: {
    fontSize: 11,
    color: colors.muted,
    marginTop: 2,
    fontWeight: '600',
  },
  profileHeroStatDivider: {
    width: 1,
    height: 32,
    backgroundColor: colors.border,
  },
  profileHeroActions: {
    flexDirection: 'row',
    gap: 10,
    width: '100%',
  },
  profileHeroBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: 11,
    borderRadius: 14,
    backgroundColor: colors.surfaceAlt,
    borderWidth: 1,
    borderColor: colors.border,
  },
  profileHeroBtnText: {
    fontSize: 13,
    fontWeight: '800',
    color: colors.primary,
  },
  menu: {
    minHeight: 60,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  menuIcon: {
    width: 40,
    height: 40,
    borderRadius: 13,
    backgroundColor: colors.surfaceAlt,
    alignItems: 'center',
    justifyContent: 'center',
  },
  communityCover: { minHeight: 190, borderRadius: 24, padding: 22, justifyContent: 'flex-end' },
  communityCoverImage: {
    ...StyleSheet.absoluteFillObject,
    width: '100%',
    height: '100%',
    borderRadius: 24,
    opacity: 0.72,
  },
  communityLogo: {
    width: 58,
    height: 58,
    borderRadius: 18,
    borderWidth: 2,
    borderColor: '#fff',
    marginBottom: 8,
  },
  circlePrivacyBadge: {
    alignSelf: 'flex-start',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    marginTop: 7,
    paddingHorizontal: 9,
    paddingVertical: 5,
    borderRadius: 10,
    backgroundColor: 'rgba(0,0,0,.34)',
  },
  circlePrivacyText: { color: '#fff', fontSize: 9, fontWeight: '900', letterSpacing: 0.6 },
  coverTitle: { color: '#fff', fontSize: 25, fontWeight: '900', marginTop: 18 },
  coverText: { color: 'rgba(255,255,255,.8)', marginTop: 4 },
  rule: { flexDirection: 'row', alignItems: 'center', gap: 10, marginTop: 12 },
  ruleNumber: {
    width: 28,
    height: 28,
    borderRadius: 14,
    textAlign: 'center',
    textAlignVertical: 'center',
    backgroundColor: colors.surfaceAlt,
    color: colors.primary,
    fontWeight: '900',
  },
  roomIcon: {
    width: 48,
    height: 48,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.surfaceAlt,
  },
  liveHeader: {
    flexDirection: 'row',
    gap: 10,
    alignItems: 'center',
    padding: 14,
    backgroundColor: colors.surface,
  },
  liveBody: { flex: 1, padding: 20, gap: 24 },
  speakerGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 24 },
  speaker: { width: 78, alignItems: 'center', gap: 5 },
  liveControls: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    padding: 14,
    backgroundColor: colors.surface,
  },
  mic: {
    width: 54,
    height: 54,
    borderRadius: 27,
    backgroundColor: colors.danger,
    alignItems: 'center',
    justifyContent: 'center',
  },
  notificationIcon: {
    width: 44,
    height: 44,
    borderRadius: 15,
    backgroundColor: colors.surfaceAlt,
    alignItems: 'center',
    justifyContent: 'center',
  },
  notificationDelete: {
    width: 38,
    height: 38,
    borderRadius: 12,
    backgroundColor: 'rgba(239, 68, 68, 0.12)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  link: { color: colors.primary, fontWeight: '800' },
  // MyCreationsScreen styles
  creationsTabBar: {
    flexDirection: 'row',
    backgroundColor: colors.surface,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
    position: 'relative',
  },
  creationsTab: {
    flex: 1,
    paddingVertical: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  creationsTabText: {
    fontSize: 13,
    fontWeight: '700',
    color: colors.muted,
  },
  creationsTabTextActive: {
    color: colors.primary,
    fontWeight: '900',
  },
  creationsTabIndicator: {
    position: 'absolute',
    bottom: 0,
    width: '50%',
    height: 3,
    borderRadius: 2,
    backgroundColor: colors.primary,
  },
  creationsPostIcon: {
    width: 38,
    height: 38,
    borderRadius: 12,
    backgroundColor: colors.surfaceAlt,
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  creationsCommunityBadge: {
    width: 46,
    height: 46,
    borderRadius: 15,
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  creationsFabContainer: {
    position: 'absolute',
    right: 20,
    width: 250,
    alignItems: 'flex-end',
    justifyContent: 'flex-end',
    gap: 0,
  },
  creationsFab: {
    width: 58,
    height: 58,
    borderRadius: 29,
    backgroundColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 8,
    shadowColor: colors.primary,
    shadowOpacity: 0.5,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 4 },
  },
  creationsFabSubRow: {
    position: 'absolute',
    bottom: 0,
    right: 5,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  creationsFabSubCircle: {
    width: 48,
    height: 48,
    borderRadius: 24,
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 6,
    shadowColor: '#000',
    shadowOpacity: 0.22,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 3 },
  },
  creationsFabSubLabel: {
    color: colors.text,
    fontSize: 13,
    fontWeight: '800',
    backgroundColor: colors.surface,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 10,
    overflow: 'hidden',
    elevation: 3,
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 2 },
  },
  creationsPostImage: {
    width: '100%',
    height: 280,
    borderRadius: 12,
    marginBottom: 4,
    backgroundColor: colors.surfaceAlt,
  },
  creationsPostTypeBadge: {
    alignSelf: 'flex-start',
    backgroundColor: colors.surfaceAlt,
    borderRadius: 8,
    paddingHorizontal: 7,
    paddingVertical: 3,
  },
  creationsPostTypeText: {
    fontSize: 10,
    fontWeight: '800',
    color: colors.muted,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  creationsCommunityHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 14,
    minHeight: 72,
    overflow: 'hidden',
  },
  creationsCommunityLogo: {
    width: 44,
    height: 44,
    borderRadius: 14,
    borderWidth: 2,
    borderColor: 'rgba(255,255,255,0.4)',
    overflow: 'hidden',
    flexShrink: 0,
  },
  headerActions: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  createCommunityCard: { gap: 16, borderColor: colors.border, backgroundColor: colors.surfaceAlt },
  blockedNotice: { flexDirection: 'row', alignItems: 'center', gap: 10 },
});
